pelatihSchema = {
    "nama": {"type": "string", "minlength": 10, "required": True, "empty": False},
    "no_kp": {"type": "string", "minlength": 12, "required": True, "empty": False},
    "no_pendaftaran": {
        "type": "string",
        "minlength": 2,
        "required": True,
        "empty": False,
    },
    "dob": {"type": "string", "required": True},
    "agama": {"type": "string", "required": True},
    "dtgSendiri": {"type": "string", "required": True},
    "yaDtg": {"type": "string", "required": False},
    "tidakDtg": {"type": "string", "required": False},
    "jantina_id": {"type": "string", "minlength": 1, "required": True, "empty": False},
    "bangsa": {"type": "string", "minlength": 1, "required": True, "empty": False},
    "bilAdik": {"type": "string", "required": True},
    "bilKeluarga": {"type": "string", "required": True},
    "alamat": {"type": "string", "minlength": 5, "required": True, "empty": False},
    "negeri": {"type": "string", "minlength": 5, "required": True, "empty": False},
    "sudahLawat": {"type": "string", "required": True},
    "keperluan": {"type": "string", "required": False},
    "no_tel": {
        "type": "list",
        "schema": {
            "type": "dict",
            "schema": {
                "no": {
                    "type": "string",
                    "minlength": 10,
                    "maxlength": 12,
                    "required": True,
                    "empty": False,
                },
                "type": {
                    "type": "string",
                    "allowed": ["rumah", "bimbit"],
                    "required": True,
                },
            },
        },
        "required": True,
    },
    "penjaga": {
        "type": "list",
        "schema": {
            "type": "dict",
            "schema": {
                "nama": {
                    "type": "string",
                    "minlength": 1,
                    "required": True,
                    "empty": False,
                },
                "noKp": {
                    "type": "string",
                    "minlength": 1,
                    "required": True,
                    "empty": False,
                },
                "dob": {
                    "type": "string",
                    "minlength": 1,
                    "required": True,
                    "empty": False,
                },
                "pekerjaan": {
                    "type": "string",
                    "minlength": 1,
                    "required": True,
                    "empty": False,
                },
                "pendapatan": {
                    "type": "string",
                    "minlength": 1,
                    "required": True,
                    "empty": False,
                },
                "hubungan": {
                    "type": "string",
                    "minlength": 1,
                    "required": True,
                    "empty": False,
                },
                "ketidakUpayaan": {"type": "string", "required": False},
                "isPenerima": {
                    "type": "string",
                    "minlength": 1,
                    "required": True,
                    "empty": False,
                },
                "bantuan": {"type": "string", "required": False},
                "kadar": {"type": "string", "required": False},
                "agensi": {"type": "string", "required": False},
            },
        },
        "required": True,
    },
    "keupayaan": {
        "type": "dict",
        "schema": {
            "tahapOKU": {"type": "string", "required": True},
            "isBantuan": {"type": "string", "required": True},
            "alatBantuan": {"type": "string", "required": False},
            "penyakit": {"type": "string", "required": False},
            "sikap": {"type": "string", "required": True},
            "lainSikap": {"type": "string", "required": False},
            "urusDiri": {
                "type": "list",
                "schema": {"type": "string"},
                "minlength": 1,
                "required": True,
            },
            "bergerak": {
                "type": "list",
                "schema": {"type": "string"},
                "minlength": 1,
                "required": True,
            },
        },
    },
    "tambahan": {
        "type": "dict",
        "schema": {
            "isSekolah": {"type": "string", "required": True},
            "sekolah": {
                "type": "dict",
                "schema": {
                    "nama": {"type": "string", "required": True},
                    "tahap": {"type": "string", "required": True},
                    "tempoh": {"type": "string", "required": True},
                    "mula": {"type": "string", "required": True},
                    "tamat": {"type": "string", "required": True},
                },
                "required": False,
            },
            "isInsitusi": {"type": "string", "required": True},
            "insitusi": {
                "type": "dict",
                "schema": {
                    "nama": {"type": "string", "required": True},
                    "tempoh": {"type": "string", "required": True},
                    "mula": {"type": "string", "required": True},
                    "tamat": {"type": "string", "required": True},
                },
                "required": False,
            },
        },
    },
}
